### ISSUE TITLE
Empty Parameters spiking since March 14th

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#54] opened 2018-03-17 00:22 UTC
We seem to have a big increase in empty utm source and entrypoints since the release of train 107.

I can't say if 107 is the cause but the date matches up:
https://analytics.amplitude.com/org/31251/chart/1ush8xd/edit/rrjg93i

It seems to start at approx 9am UTC (1am pacific).

It also seems to spike every day at the same time.

Any thoughts?

**Comment by davismtl** [comment] 2018-03-17 00:22
CC @irrationalagent

**Comment by davismtl** [comment] 2018-03-17 00:32
Also posted in Bugzilla with moz org team:
https://bugzilla.mozilla.org/show_bug.cgi?id=1446573

**Comment by philbooth** [comment] 2018-03-17 07:47
Looking at the [deploy log](https://philbooth.me/fxa#deployments), I don't think 107 went out until about 12 hours after this started happening. Auth server was just before 9pm UTC, followed by OAuth, profile and content servers shortly after.

Also, the way the first two spikes return to normal levels after a brief period suggests to me this is not something introduced by an FxA deployment.

And even though the third, much bigger spike (16th March) looks like it roughly coincides with the auth server 107.3 patch, I'm pretty sure that's coincidence. Nothing from that (very focused) patch could affect this.

**Comment by davismtl** [comment] 2018-03-17 19:17
Today's numbers seem to clearly indicate that it is something broken with /firstrun

The blue unknown is cannibalizing the green firstrun:

<img width="606" alt="screen shot 2018-03-17 at 12 16 18 pm" src="https://user-images.githubusercontent.com/19537086/37559092-14c1abc4-29dd-11e8-8302-ec95b54b72ce.png">

**Comment by davismtl** [comment] 2018-03-17 20:02
Further investigation has me believe that this is more general than first run:
https://analytics.amplitude.com/org/31251/chart/1ush8xd/edit/4u29i75

In fact the times seem to perfectly match up with what I am observing from the form views:
https://github.com/mozilla/fxa-amplitude-send/issues/55

**Comment by davismtl** [comment] 2018-03-17 20:50
Super strange caveat:

This seems to mostly only impact registration numbers.

Login numbers (by utm_source and entrypoint) seem pretty intact:
https://analytics.amplitude.com/org/31251/chart/2ngrhz1/edit/cjt2wao  

Maybe that will give us a lead on the cause.

**Comment by irrationalagent** [comment] 2018-03-17 21:18
related to https://github.com/mozilla/fxa-amplitude-send/issues/55

here's a re:dash version
https://sql.telemetry.mozilla.org/queries/52067/source#138957

somehow the utm_source =.whatsnew seems to be getting lost before getting into amplitude, as re:dash seems to indicate that's the cause of the registration increase.

grouping by entrypoint tells the same story:
https://sql.telemetry.mozilla.org/queries/52068/source#138959

**Comment by rfk** [comment] 2018-03-19 01:31
> BTW super dumb q: how do i get to the what's new page?

You can visit it directly at:  https://www.mozilla.org/en-US/firefox/59.0/whatsnew/

**Comment by chrismore** [comment] 2018-03-19 11:48
This is the most recent commit I can find regarding /firstrun/, but I don't see any modification to the entrypoint=firstrun parameter: https://github.com/mozilla/bedrock/commit/50dd40bf6fcd1d89c4f9bc74aadf6280efebd4d8

**Comment by irrationalagent** [comment] 2018-03-19 15:01
https://sql.telemetry.mozilla.org/queries/52066/source#138955
We got crazy traffic through what's new over the weekend.

Looking here:
https://analytics.amplitude.com/org/31251/chart/1ush8xd/edit/4u29i75

We lose the utm parameters right on the upswing of the traffic each time, which does make me think this might be a rate-limiting or related problem, as phil notes in #55 
![screenshot-2018-3-19_fxa_registration_by_utm_source_-_amplitude_edit](https://user-images.githubusercontent.com/5625313/37603403-1f016e8a-2b54-11e8-9804-0fee643c8b3b.png)

**Comment by jbuck** [comment] 2018-03-19 23:59
@irrationalagent very good guess, you're pretty much spot on... but the limit we hit wasn't what you'd expect: It was disk burst IO limits on each content server instance we hit.

Take a look at a content sever disk stats: 

![screenshot 2018-03-19 19 41 50](https://user-images.githubusercontent.com/578466/37628215-eb679544-2bae-11e8-9176-f1cf29679d63.png)

When the instance starts Write IOPS are humming along at 600-800 until the Burst Balance drops to 0%. Once that happens, the disk is limited to 150 IOPS. On one instance I checked, it was 3 hours behind real-time in sending logs to Kinesis, with a constant 50% iowait.

This also explains why logs work for the first few hours of an traffic increase - when we increase traffic we'll scale up and add more instances which are able to send some logs for approximately 2-3 hours until they run out of burst credits.

I've spun up a new content server stack that has 10x more IOPS and should handle the load just fine. We'll know for sure tomorrow, but I'm 95% confident that's the fix needed here and for #55

**Comment by vladikoff** [comment] 2018-03-20 00:05
@jbuck woooo!

**Comment by davismtl** [comment] 2018-03-20 00:43
Awesome investigation @irrationalagent and @jbuck !

**Comment by philbooth** [comment] 2018-03-20 07:23
Being worked on in #56, closing this one.

**Closed by philbooth** 2018-03-20 07:23 UTC
Labels: train-109, waffle:active
