### ISSUE TITLE
Amplitude not pulling in data for  event: fxa_login-forgot_submit

### ISSUE THREAD

**Issue by medinacana** [mozilla/fxa-amplitude-send#65] opened 2018-06-20 18:19 UTC
It seems as though the event `fxa_login-forgot_submit` in amplitude is not pulling in any data. When you select the event, Amplitude returns a “No data available” message. 

We first noticed this while creating the following two charts:
https://analytics.amplitude.com/mozilla-corp/chart/new/ij2u0jg
https://analytics.amplitude.com/mozilla-corp/chart/new/0n6457l

**Comment by philbooth** [comment] 2018-06-20 18:34
Interesting, thanks.

Looking at the equivalent flow event from which the Amplitude event is generated, they seemed to stop on March 5th, which corresponds with FxA train 106:

https://sql.telemetry.mozilla.org/queries/55670/source#146224

I'll dig into it some more tomorrow to figure out what the problem is, maybe a view name got changed or something.

**Comment by philbooth** [comment] 2018-06-22 10:36
Fix for this is incoming, should go into train 115.

**Closed** 2018-06-25 17:18 UTC
Labels: waffle:review
