### ISSUE TITLE
Fix UTM params in Amplitude

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#27] opened 2017-11-07 22:20 UTC
Since October 24th, we don't seem to be collecting the utm parameters properly in Amplitude.

https://analytics.amplitude.com/org/31251/chart/oirl9vh/edit/1ol1yvn

At first I thought it was caused by marketing's A/B test but since they stopped it, they've put the page back to what it was and we seem to still be experiencing problems.

I confirm that I can see the utm params in the iFrame URL on /firstrun

Our redash numbers also seem to be experiencing the same problems.
https://sql.telemetry.mozilla.org/queries/1975#3535

**Comment by davismtl** [comment] 2017-11-07 22:22
Oops, that redash is using entrypoint and not utm but the point is still valid.

**Comment by vladikoff** [comment] 2017-11-07 22:34
cc @philbooth

**Comment by rfk** [comment] 2017-11-08 04:43
> Our redash numbers also seem to be experiencing the same problems.

I modified this graph to include a specific "(none)" option, as it was previously lumped in with "other".  There's a definite rise in no-entrypoint signups from early November:

  https://sql.telemetry.mozilla.org/queries/1975/source#3535

**Comment by philbooth** [comment] 2017-11-08 11:22
I don't think we broke anything. No related code has changed recently from what I can see.

If I add a `utm_source` param when running in local dev, it shows up in the content server logs for amplitude events:

```
{"op":"amplitudeEvent","time":1510138626335,"device_id":"8f66dccecf4e4beebc077fa7a0c80571","event_type":"fxa_reg - view","session_id":1510138625527,"event_properties":{"device_id":"8f66dccecf4e4beebc077fa7a0c80571","service":"sync"},"user_properties":{"ua_browser":"Firefox","ua_version":"58","entrypoint":"menupanel","experiments":["q3form_changes_signup_password_confirm","signup_password_confirm_control"],"flow_id":"cf9d68d266cae00013a21962c0c62aaf85a436ea1cc9da385736ca2d16d3d3cd","utm_source":"firstrun"},"app_version":"99","language":"fr","os_name":"Mac OS X","os_version":"10.11"}
{"op":"amplitudeEvent","time":1510138630015,"device_id":"8f66dccecf4e4beebc077fa7a0c80571","event_type":"fxa_reg - engage","session_id":1510138625527,"event_properties":{"device_id":"8f66dccecf4e4beebc077fa7a0c80571","service":"sync"},"user_properties":{"ua_browser":"Firefox","ua_version":"58","entrypoint":"menupanel","experiments":["q3form_changes_signup_password_confirm","signup_password_confirm_control"],"flow_id":"cf9d68d266cae00013a21962c0c62aaf85a436ea1cc9da385736ca2d16d3d3cd","utm_source":"firstrun"},"app_version":"99","language":"fr","os_name":"Mac OS X","os_version":"10.11"}
{"op":"amplitudeEvent","time":1510138640139,"device_id":"8f66dccecf4e4beebc077fa7a0c80571","event_type":"fxa_reg - submit","session_id":1510138625527,"event_properties":{"device_id":"8f66dccecf4e4beebc077fa7a0c80571","service":"sync"},"user_properties":{"ua_browser":"Firefox","ua_version":"58","entrypoint":"menupanel","experiments":["q3form_changes_signup_password_confirm","signup_password_confirm_control"],"flow_id":"cf9d68d266cae00013a21962c0c62aaf85a436ea1cc9da385736ca2d16d3d3cd","utm_source":"firstrun"},"app_version":"99","language":"fr","os_name":"Mac OS X","os_version":"10.11"}
```

...and for flow events:

```
{"event":"flow.begin","flow_id":"77029fa48054422b1d08f2ad9b1eeda8cc1ecd56b897ae96809af67ade659f9b","flow_time":0,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":30341,"time":"2017-11-08T11:02:09.501Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync","utm_source":"firstrun"}
{"event":"flow.signup.view","flow_id":"77029fa48054422b1d08f2ad9b1eeda8cc1ecd56b897ae96809af67ade659f9b","flow_time":787,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":30341,"time":"2017-11-08T11:02:10.288Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync","utm_source":"firstrun"}
{"event":"flow.signup.engage","flow_id":"77029fa48054422b1d08f2ad9b1eeda8cc1ecd56b897ae96809af67ade659f9b","flow_time":2903,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":30341,"time":"2017-11-08T11:02:12.404Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync","utm_source":"firstrun"}
{"event":"flow.signup.submit","flow_id":"77029fa48054422b1d08f2ad9b1eeda8cc1ecd56b897ae96809af67ade659f9b","flow_time":10173,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":30341,"time":"2017-11-08T11:02:19.674Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync","utm_source":"firstrun"}
{"event":"flow.signup.attempt","flow_id":"77029fa48054422b1d08f2ad9b1eeda8cc1ecd56b897ae96809af67ade659f9b","flow_time":11864,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":30341,"time":"2017-11-08T11:02:21.365Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync","utm_source":"firstrun"}
{"event":"flow.choose-what-to-sync.view","flow_id":"77029fa48054422b1d08f2ad9b1eeda8cc1ecd56b897ae96809af67ade659f9b","flow_time":12160,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":30341,"time":"2017-11-08T11:02:21.661Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync","utm_source":"firstrun"}
{"event":"flow.experiment.q3FormChanges.signupPasswordConfirm","flow_id":"77029fa48054422b1d08f2ad9b1eeda8cc1ecd56b897ae96809af67ade659f9b","flow_time":13484,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":30341,"time":"2017-11-08T11:02:22.985Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync","utm_source":"firstrun"}
{"event":"flow.experiment.signupPasswordConfirm.control","flow_id":"77029fa48054422b1d08f2ad9b1eeda8cc1ecd56b897ae96809af67ade659f9b","flow_time":13484,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":30341,"time":"2017-11-08T11:02:22.985Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync","utm_source":"firstrun"}
{"event":"flow.confirm.view","flow_id":"77029fa48054422b1d08f2ad9b1eeda8cc1ecd56b897ae96809af67ade659f9b","flow_time":13494,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":30341,"time":"2017-11-08T11:02:22.995Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync","utm_source":"firstrun"}
{"event":"flow.experiment.sendSms.signinCodes","flow_id":"77029fa48054422b1d08f2ad9b1eeda8cc1ecd56b897ae96809af67ade659f9b","flow_time":24649,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":30341,"time":"2017-11-08T11:02:34.150Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync","utm_campaign":"fx-welcome","utm_content":"fx-activate","utm_medium":"email","utm_source":"email"}
{"event":"flow.experiment.q3FormChanges.signupPasswordConfirm","flow_id":"77029fa48054422b1d08f2ad9b1eeda8cc1ecd56b897ae96809af67ade659f9b","flow_time":24660,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":30341,"time":"2017-11-08T11:02:34.161Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync","utm_campaign":"fx-welcome","utm_content":"fx-activate","utm_medium":"email","utm_source":"email"}
{"event":"flow.experiment.signupPasswordConfirm.control","flow_id":"77029fa48054422b1d08f2ad9b1eeda8cc1ecd56b897ae96809af67ade659f9b","flow_time":24662,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":30341,"time":"2017-11-08T11:02:34.163Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync","utm_campaign":"fx-welcome","utm_content":"fx-activate","utm_medium":"email","utm_source":"email"}
{"event":"flow.sms.view","flow_id":"77029fa48054422b1d08f2ad9b1eeda8cc1ecd56b897ae96809af67ade659f9b","flow_time":24711,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":30341,"time":"2017-11-08T11:02:34.212Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync","utm_campaign":"fx-welcome","utm_content":"fx-activate","utm_medium":"email","utm_source":"email"}
```

And for prod, I can see them showing up in Kibana:

https://kibana-fxa-us-west-2.prod.mozaws.net/#/dashboard/elasticsearch/Content%20server%20flow%20events

And if we broke it in the code, I'd expect the numbers in your charts to be zero. But yesterday, for instance, there were 3,208 `fxa_reg - complete` events where `utm_source` was `firstrun`, according to Amplitude.

**Comment by philbooth** [comment] 2017-11-08 11:29
Also, here is a chart in redash showing flows segmented by `utm_term`, which appears to be sane:

https://sql.telemetry.mozilla.org/queries/48786/source#131514

**Comment by davismtl** [comment] 2017-11-08 18:07
Filed a bug with Mozilla.org team: https://bugzilla.mozilla.org/show_bug.cgi?id=1415622

**Comment by davismtl** [comment] 2017-11-08 18:49
@philbooth 
After further investigation, all of our UTM sources seem to have broken at the same time. It was just less apparent since firstrun is so big in comparison.

https://analytics.amplitude.com/org/31251/chart/p9li5df/edit/x74s3w6

![screen shot 2017-11-08 at 10 48 29 am](https://user-images.githubusercontent.com/19537086/32568203-65705adc-c472-11e7-9f65-ab81abdcb5f0.png)

@philbooth This further leads me to believe that the problem is likely on our end.

**Comment by davismtl** [comment] 2017-11-11 01:19
@rfk @philbooth What do you propose we do here. To be frank, I'm a bit worried here because I don't feel very confident in our ability to measure firstrun properly going into the release of 57. If anything goes wrong with the new firstrun page that will be released, will be able to accurately catch it?

1) Our UTM parameters are all over the place so we can't filter out firstrun alone.
2) We have an unexpected drop in firstrun entrypoints that did not recover after marketing's A/B test was turned off AND a growing number of empty entrypoints since the test was turned off: https://sql.telemetry.mozilla.org/queries/1975/source#3535
3) We have a growing number of empty utm parameters 

I made a new dashboard to get the big picture (see bloew). The bright side in all of this is that I don't think that there is anything functionally broken. If I look at the overall login and registration numbers, they seem pretty steady. One thing that does stand out is our form views  are more volatile than they use to be. (up, down, up down) They were more steady before October 24th with dips on weekends. For example, we see a big drop on Wednesday this week. When comparing to the GA numbers of /firstrun, there is way less volatility in the traffic numbers than we are observing in ours. (Assuming that 1 form view = 1 page view).

https://analytics.amplitude.com/org/31251/dashboard/nz0rp3d

**Comment by davismtl** [comment] 2017-11-11 01:19
CC @irrationalagent

**Comment by philbooth** [comment] 2017-11-11 09:46
My suspicion is that this is caused by invalid utm params (could be any of them, not just source) being sent to us from outside.

I suspect it for a few reasons:

* The nature of the "breaks". They seem to come and go while we're doing nothing that could possibly affect them. No content server changes were deployed on many of the days where the graphs jag down or back up again (the auth server doesn't set utm params on amplitude events).

* The nature of our metrics-handling code. It's hard to conceive of a way that this could break in such a way as to affect some utm values but not others. If any of that code is broken, it will be broken for everything.

* That nature of the content server's metrics validation. If any of the properties in the front-end metrics bundle are invalid, we disregard the whole thing and don't emit any events. This is necessary because we receive so much spurious/malicious traffic to that endpoint, we need to be brutal about what we accept. For the utm params that means at most 128 characters long and they can contain only letters, numbers and the following punctuation characters: `_`, `/`, `.`, `%`, `-`. Whitespace or any other characters will cause them to fail validation.

Obviously that last bullet is the key one but it's hard to verify as the cause. By definition those events will be dropped invisibly. Maybe it's possible for the two j's to find out from the content server logs.

I also don't know how/when/if those validation rules were conveyed to the other team(s) that need to know about them. This stuff should all be documented somewhere but I'm not sure it is.

Lastly, re: your point about the discrepancy with GA, I think that's expected and I think the numbers in GA (and DataDog for that matter) may be less reliable than the numbers in Redshift and Amplitude. We do extra validation for flow and amplitude events which disregards data that passed initial validation but has other signals that indicate it didn't originate from legitimate traffic. Whatever discrepancy exists is probably due to that, so I trust what we have in Amplitude/Redshift more than GA/DataDog (but am willing to be persuaded otherwise).

**Comment by philbooth** [comment] 2017-11-11 10:03
> For the utm params that means at most 128 characters long and they can contain only letters, numbers and the following punctuation characters: `_`, `/`, `.`, `%`, `-`. Whitespace or any other characters will cause them to fail validation.

And I just noticed an additional condition that also permits the literal string:

```
page+referral+-+not+part+of+a+campaign
```

**Comment by rfk** [comment] 2017-11-13 01:14
As far as I can tell, this utm_source jank is specific to amplitude.  If I look at reg_complete in re:dash then I see the same broad trends, but not the day-to-day spikes between (none) and firstrun:

  https://sql.telemetry.mozilla.org/queries/48972/source#131919

If we look further up the registration funnel, it seems that the utm_source weirdness only appears after account creation.  This dashboard has event counts grouped by utm_source, excluding (none) and firstrun, for each of reg-view, reg-submit, reg-created, and reg-complete:

  https://analytics.amplitude.com/org/31251/dashboard/qqajiv2

Note that reg-view and reg-submit appear to have pretty sane trends, while reg-created and reg-complete have wild variations, including some days where there are basically no events with non-none utm_source values.

I'm wondering if this is due to the way amplitude is handling utm_source as a "user property".  IIUC, the value of utm_source for any particular event, will be the value that it was most recently set to at the user level, before the event occurred.  Is it possible that some other event is occurring before the reg-created and re-setting utm_souce to none for that user?  I don't see why it would vary day-to-day, but at this stage I'll believe just about anything is possible...

**Comment by rfk** [comment] 2017-11-13 01:17
> One thing that does stand out is our form views are more volatile than they use to be.
> (up, down, up down) They were more steady before October 24th with dips on weekends.
> For example, we see a big drop on Wednesday this week. 

I'm also not really able to reproduce this in re:dash, see e.g. the amplitude graph with wild fluctuations:

  https://analytics.amplitude.com/org/31251/chart/5ldlx0m/edit/qdd6itw

Versus (my best attempt at) the same graph from re:dash which much smoother weekly pattern:

  https://sql.telemetry.mozilla.org/queries/48970/source#131915

Which makes me wonder if we've lost some events in the amplitude export for those days.

**Comment by philbooth** [comment] 2017-11-13 14:24
> As far as I can tell, this utm_source jank is specific to amplitude... Which makes me wonder if we've lost some events in the amplitude export for those days.

@jbuck, have there been any errors in the amplitude import process that you've seen? Especially for the following dates, if I'm reading Ryan's chart correctly.

* October: 25th, 26th, 31st
* November: 1st, 2nd, 3rd, 6th, 8th, 10th

**Comment by davismtl** [comment] 2017-11-13 17:37
> If we look further up the registration funnel, it seems that the utm_source weirdness only appears after account creation. This dashboard has event counts grouped by utm_source, excluding (none) and firstrun, for each of reg-view, reg-submit, reg-created, and reg-complete:
>
>https://analytics.amplitude.com/org/31251/dashboard/qqajiv2

This is the most revealing part to me!

We are getting the right `utm` params earlier in the funnel. This leads me to believe that mozilla.org is passing us the right data. If the problem was in the params they passed us, we wouldn't have them for form views. It seems to break for the `created` and `complete` events.

**Comment by philbooth** [comment] 2017-11-21 08:22
Fwiw, although it's not to the same extent as the Amplitude charts, I have noticed similarly-shaped weirdness in some Redash charts, which is interesting.

`utm_source` definitely looks wrong here, for instance:

https://sql.telemetry.mozilla.org/queries/48786/source#131514

**Comment by rfk** [comment] 2017-11-27 04:06
Relatedly, something seems to have gone wrong with "entrypoint" on Nov 21, judging by this graph:

  https://analytics.amplitude.com/org/31251/chart/luluy01

<img width="1240" alt="capture" src="https://user-images.githubusercontent.com/34695/33250427-8d202fe6-d384-11e7-826b-4c37d09eff07.PNG">

**Comment by rfk** [comment] 2017-11-27 04:54
The same effect can be seen for utm_source BTW, starting Nov 21.  Take a look at e.g. the bottom two graphs here:

  https://analytics.amplitude.com/org/31251/dashboard/qqajiv2

**Comment by philbooth** [comment] 2017-11-27 06:53
For `entrypoint` I think that is a result of this change, which shipped in train 100 late on the 20th November: mozilla/fxa-content-server#5684

Stupidly, I didn't think of the effect it would have on existing graphs. I should have retained it as an event property for backwards compatibility  (in addition to the user property I mean). Want me to put it back in now?

**Comment by vladikoff** [comment] 2017-11-27 21:19
from mtg: need help from @jbuck on this one. Could be at all hands.

**Comment by rfk** [comment] 2017-11-29 08:23
> For entrypoint I think that is a result of this change, which shipped in train 100 late on the 20th
> November: mozilla/fxa-content-server#5684

Confirmed, if we switch the graph to use a user-property entrypoint then this effect goes away; we'll just need to update any existing graphs that are using it as an event property.

**Comment by vladikoff** [comment] 2017-12-18 21:01
from mtg: @jbuck moving to a node.js sender to get better logging...

Dashboard to look at https://analytics.amplitude.com/org/31251/dashboard/qqajiv2

**Comment by vladikoff** [comment] 2017-12-18 21:02
from mtg: blocked until we know what is going on...

**Comment by philbooth** [comment] 2018-01-08 13:27
In mozilla/fxa-content-server#5789, we shipped logging that should let us know the extent to which payload validation is affecting our metrics. The `op` to look for in Kibana is `validation.failed`, but my Kibana-fu has gone very rusty since I last used it and I can't make it do what I want.

Or maybe there really are no validation errors logged because of something stupid I did in the code. Works okay locally though.

The third alternative, which is supremely unlikely, is that there really are no validation errors because no payloads have failed validation.But  I find that borderline-impossible to believe.

**Comment by vladikoff** [comment] 2018-01-08 21:06
from mtg: waiting for train deploy

**Comment by philbooth** [comment] 2018-01-18 18:34
Earlier on, me and @jbuck had a debug session over Vidyo about this. No eureka moments yet, but I wanted to summarise what we talked about and where we got to.

First we looked at two pairs of charts that demonstrate the problem:

1. "FxA: account.created" shows that the raw event counts are similar:
   1. [in Amplitude](https://analytics.amplitude.com/org/31251/chart/s6y09vo);
   2. [and in Redash](https://sql.telemetry.mozilla.org/queries/50280/source#135022).

2. But "FxA: account.created with utm_source set" shows a discrepancy in the UTM params:
   1. [in Amplitude](https://analytics.amplitude.com/org/31251/chart/5bfux0l/);
   2. [and in Redash](https://sql.telemetry.mozilla.org/queries/50281/source#135023).

A fifth chart shows the problem is specific to events from the auth server: [FxA: signup.view with utm_source set](https://analytics.amplitude.com/org/31251/chart/rbg0ilh).

This suggests that user properties aren't always propagating from the earlier content server events to the later auth server events. We had two hypotheses for why that might be the case:

1. Maybe something is wrong with the device_id property that we're sending to Amplitude. It's generated by the content server and then sent to the auth server so the same value can be used in both places. If there's any discontinuity in that value it would prevent Amplitude from linking together the user properties.

2. Or perhaps the event timestamps are out of whack between the two servers. Amplitude only shows user properties on events that occur after the point where the property was set. And the content server has logic for estimating the timestamp (because those events occur on the client), so there's plenty of scope for something to go wrong here.

We dug into the first hypothesis a bit and verified that the `device_id` stuff is working correctly on stage for Amplitude to tie the events together. For instance, [this](https://analytics.amplitude.com/org/31251/project/178230/search/40947895484) is an example event flow we went through where it's working correctly.

We also had a closer look at the raw logs for specific times where it was and wasn't working. For example, [this chart](https://analytics.amplitude.com/org/31251/chart/gwqcogc) identifies that on the 16th January there are no UTM params but on the 17th there's a whole bunch of them. Nothing concrete came out of this yet but there's still more digging we can do to try and zero in on the failing cases. It's tricky because the logs contain unhashed data so the `device_id` and `user_id` we see in Amplitude are different to the ones in the logs.

Something we didn't do during the debug session was dig into the second hypothesis at all. @jbuck, how tricky would it be to look for an `fxa_reg - submit` and an `fxa_reg - created` that share the same `device_id` but are in the wrong order in the logs? (i.e. `submit` is later than `created`)

**Comment by philbooth** [comment] 2018-01-23 15:16
Another part of this issue to consider is when it started happening. The first date that exhibits a drop is 25th October. There was no deployment on that day, or on the 24th, but train 98 did go out on the 23rd October.

It's hard to imagine a problem in train 98 that wouldn't show up until a couple of days after the deployment but, for completeness, these are all of the metrics-related changes from train 98:

* https://github.com/mozilla/fxa-content-server/commit/ae97461
* https://github.com/mozilla/fxa-content-server/commit/4d194c1
* https://github.com/mozilla/fxa-content-server/commit/8c221f2
* https://github.com/mozilla/fxa-content-server/commit/aa0a297
* https://github.com/mozilla/fxa-content-server/commit/4b8355a
* https://github.com/mozilla/fxa-content-server/commit/ba39aeb
* https://github.com/mozilla/fxa-auth-server/commit/c60f198
* https://github.com/mozilla/fxa-auth-server/commit/5be3475

I've been through them, they all seem pretty innocuous and are covered by tests too.

Also interesting is the pattern of failure. Initially it looks like the odd day here or there, then it seems to get worse until every day is affected:

![Screen shot showing the problem with UTM parameters getting progressively worse from the 25th October](https://user-images.githubusercontent.com/64367/35283402-1499d7b8-0050-11e8-98b9-fcb6f90fa58b.png)

@jbuck, given the code changes seem unremarkable, can you think of anything operationally that might have started happening on the 25th or late on the 24th October?

**Comment by philbooth** [comment] 2018-01-23 16:12
> This suggests that user properties aren't always propagating from the earlier content server events to the later auth server events. We had two hypotheses for why that might be the case:
> 
> 1. Maybe something is wrong with the device_id property that we're sending to Amplitude. It's generated by the content server and then sent to the auth server so the same value can be used in both places. If there's any discontinuity in that value it would prevent Amplitude from linking together the user properties.
> 
> 2. Or perhaps the event timestamps are out of whack between the two servers. Amplitude only shows user properties on events that occur after the point where the property was set. And the content server has logic for estimating the timestamp (because those events occur on the client), so there's plenty of scope for something to go wrong here.

A third hypothesis:

3. I'm not certain it would lead to these symptoms but maybe the `session_id` doesn't match between the content or auth servers, or perhaps it is missing in the auth server for some reason.

@jbuck, that's another one we can try grepping the logs for when you have some time.

**Comment by davismtl** [comment] 2018-01-24 17:57
I revived this yesterday because I observed that utm-source was not in page source on firstrun:

https://bugzilla.mozilla.org/show_bug.cgi?id=1415622

**Comment by philbooth** [comment] 2018-01-26 12:26
> I revived this yesterday because I observed that utm-source was not in page source on firstrun:
>
> https://bugzilla.mozilla.org/show_bug.cgi?id=1415622

:+1:

Thanks to some sterling grep-fu by @jbuck, we've produced a chart that shows the extent to which that regression contributes to the problems visible in Amplitude. It's not that interesting in and of itself, but from a dev perspective it tells us a few things:

1. An issue definitely still exists *after* the data has entered FxA.
2. The reduced height of the more recent peaks we see on the Amplitude [chart](https://analytics.amplitude.com/org/31251/chart/5bfux0l) *can* be at least partially attributed to the regression.
3. For debugging and comparison purposes, we can safely treat those more recent peaks as "good" days, when the problem occurred less frequently. This is useful both because the reduced event counts for those makes it easier to sift through the data, and because there are boring technical reasons why debugging more recent data is easier for us.

Anyway, this is the chart, showing the count of sign-up submit events that have `utm_source` set, based on grepping through the raw logs:

https://sql.telemetry.mozilla.org/queries/50410/source#135342

And this is the equivalent data in Amplitude:

https://analytics.amplitude.com/org/31251/chart/rbg0ilh

Previously the big drop in the Amplitude chart was confusing our debugging somewhat, because we didn't know if it represented an additional problem in our codebase.

**Comment by philbooth** [comment] 2018-01-26 12:32
@jbuck, I've updated the script in #39 to hopefully produce some more useful numbers for us. Let's use it to dig into Wednesday 17th January ("good" day) and Thursday 18th January ("bad" day) when you have time.

**Comment by jbuck** [comment] 2018-01-26 21:50
@philbooth I ran the script with my changes to handle multiple files in #41

```
$ node ~/bin/check-events.js fxa-content/2018/01/17/12/ fxa-auth/2018/01/17/12/
EVENTS: 1073589 (100%)
  content: 91087 (100%)
  auth: 982502 (100%)
MISSING user_id AND device_id AND session_id: 0 (0%)
  content: 0 (0%)
  auth: 0 (0%)
MISSING user_id AND device_id: 0 (0%)
  content: 0 (0%)
  auth: 0 (0%)
MISSING user_id AND session_id: 136 (0%)
  content: 0 (0%)
  auth: 136 (0%)
MISSING device_id AND session_id: 956781 (89%)
  content: 0 (0%)
  auth: 956781 (97%)
MISSING user_id: 77709 (7%)
  content: 77550 (85%)
  auth: 159 (0%)
MISSING device_id: 5736 (1%)
  content: 0 (0%)
  auth: 5736 (1%)
MISSING session_id: 229 (0%)
  content: 0 (0%)
  auth: 229 (0%)
FUTURE session_id: 15234 (1%)
  content: 13598 (15%)
  auth: 1636 (0%)
FUTURE time: 504761 (47%)
  content: 20088 (22%)
  auth: 484673 (49%)
CONFLICTING user_id: 27 (0%)
CONFLICTING device_id: 7579 (1%)
CONFLICTING session_id: 0 (0%)
```

```
$ node ~/bin/check-events.js fxa-content/2018/01/18/12/ fxa-auth/2018/01/18/12/
EVENTS: 1036536 (100%)
  content: 29053 (100%)
  auth: 1007483 (100%)
MISSING user_id AND device_id AND session_id: 0 (0%)
  content: 0 (0%)
  auth: 0 (0%)
MISSING user_id AND device_id: 0 (0%)
  content: 0 (0%)
  auth: 0 (0%)
MISSING user_id AND session_id: 136 (0%)
  content: 0 (0%)
  auth: 136 (0%)
MISSING device_id AND session_id: 982820 (95%)
  content: 0 (0%)
  auth: 982820 (98%)
MISSING user_id: 25031 (2%)
  content: 24783 (85%)
  auth: 248 (0%)
MISSING device_id: 5483 (1%)
  content: 0 (0%)
  auth: 5483 (1%)
MISSING session_id: 172 (0%)
  content: 0 (0%)
  auth: 172 (0%)
FUTURE session_id: 1368 (0%)
  content: 0 (0%)
  auth: 1368 (0%)
FUTURE time: 439467 (42%)
  content: 0 (0%)
  auth: 439467 (44%)
CONFLICTING user_id: 0 (0%)
CONFLICTING device_id: 0 (0%)
CONFLICTING session_id: 0 (0%)
```

**Comment by philbooth** [comment] 2018-01-30 07:43
:tada:🎆:man_dancing: 

Here is some pretty solid evidence that mozilla/fxa-auth-server#2267, deployed in train 104 last night, has improved this situation significantly:

<img width="1299" alt="Screen shot showing an increase in the number of complete events that have utm_source set, coinciding with the deployment of train 104" src="https://user-images.githubusercontent.com/64367/35553702-dbc3246c-0590-11e8-94f0-2668001076e6.png" />

https://analytics.amplitude.com/org/31251/chart/d6tjmiu

**Comment by philbooth** [comment] 2018-01-30 20:52
Popping this in here for tomorrow so I don't lose it in IRC scrollback:

```
$ check-events.js fxa-auth/2018/01/29/12/ fxa-content/2018/01/29/12/
EVENTS: 1076964 (100%)
  content: 28412 (100%)
  auth: 1048552 (100%)
MISSING user_id AND device_id AND session_id: 0 (0%)
  content: 0 (0%)
  auth: 0 (0%)
MISSING user_id AND device_id: 0 (0%)
  content: 0 (0%)
  auth: 0 (0%)
MISSING user_id AND session_id: 139 (0%)
  content: 0 (0%)
  auth: 139 (0%)
MISSING device_id AND session_id: 1022931 (95%)
  content: 0 (0%)
  auth: 1022931 (98%)
MISSING user_id: 24295 (2%)
  content: 24193 (85%)
  auth: 102 (0%)
MISSING device_id: 5696 (1%)
  content: 0 (0%)
  auth: 5696 (1%)
MISSING session_id: 188 (0%)
  content: 0 (0%)
  auth: 188 (0%)
FUTURE session_id: 1722 (0%)
  content: 0 (0%)
  auth: 1722 (0%)
FUTURE time: 562497 (52%)
  content: 0 (0%)
  auth: 562497 (54%)
CONFLICTING user_id: 0 (0%)
CONFLICTING device_id: 0 (0%)
CONFLICTING session_id: 0 (0%)
```

```
$ check-events.js fxa-auth/2018/01/30/12/ fxa-content/2018/01/30/12/
EVENTS: 1145692 (100%)
  content: 98278 (100%)
  auth: 1047414 (100%)
MISSING user_id AND device_id AND session_id: 0 (0%)
  content: 0 (0%)
  auth: 0 (0%)
MISSING user_id AND device_id: 0 (0%)
  content: 0 (0%)
  auth: 0 (0%)
MISSING user_id AND session_id: 136 (0%)
  content: 0 (0%)
  auth: 136 (0%)
MISSING device_id AND session_id: 1019748 (89%)
  content: 0 (0%)
  auth: 1019748 (97%)
MISSING user_id: 83672 (7%)
  content: 83576 (85%)
  auth: 96 (0%)
MISSING device_id: 6090 (1%)
  content: 0 (0%)
  auth: 6090 (1%)
MISSING session_id: 226 (0%)
  content: 0 (0%)
  auth: 226 (0%)
FUTURE session_id: 18909 (2%)
  content: 17011 (17%)
  auth: 1898 (0%)
FUTURE time: 587230 (51%)
  content: 24841 (25%)
  auth: 562389 (54%)
CONFLICTING user_id: 32 (0%)
CONFLICTING device_id: 8022 (1%)
CONFLICTING session_id: 0 (0%)
```

**Comment by philbooth** [comment] 2018-01-31 10:42
It's weird that the artifact I'm attributing to the success of mozilla/fxa-auth-server#2267 in Amplitude also shows up in Redash.

* Amplitude: https://analytics.amplitude.com/org/31251/chart/rmrorzl
* Redash: https://sql.telemetry.mozilla.org/queries/50482/source#135481

I can't imagine any weird cocktail of conditions that should make it show up there. What does it mean?

Maybe it's an outlandish coincidence that the firstrun `utm_source` fix was made at the same time we deployed train 104. If that is the case, it's difficult to know what effect train 104 had in and of itself.

Or maybe I just don't understand how utm params are getting in to Redshift properly. Perhaps there's something wrong in the content server that meant they weren't always being sent with those events.

**Comment by philbooth** [comment] 2018-01-31 10:49
> Or  maybe I just don't understand how utm params are getting in to Redshift  properly. Perhaps there's something wrong in the content server that  means they aren't always being sent with those events.

No, that can't be it because it also shows up in the content server events in Amplitude:

https://analytics.amplitude.com/org/31251/chart/u6w5c4d

Maybe the firstrun team really did deploy at the same time as train 104??

**Comment by davismtl** [comment] 2018-01-31 17:53
@philbooth 

Correct me if I'm wrong. At a first glance, they seem to both change at EXACTLY the same time at 5pm on the 29th.

However, I believe that Re:Dash is in UTC and Amplitude is in Pacific time.
![image](https://user-images.githubusercontent.com/19537086/35638050-e67a1656-066a-11e8-86f7-4300cf134c99.png)

This would lead me to think that the first spike we see on on Re:Dash never really show up on Amplitude. If I do +8h to Amplitude, that takes us to 1-2am on Re:Dash and then the chart makes sense. It explain the initial dip in Amplitude and then the spike.

**Comment by philbooth** [comment] 2018-02-02 13:50
Having finished going through all the metrics-related code in the content and auth servers, I'm tentatively moving this back to `next` while we wait to see the long-term effect on the charts in Amplitude.

Early signs are good, it looks like we're heading for our fourth consecutive day of plausible numbers as I write this. (they're slightly lower in Amplitude but way better than previously)

**Comment by vladikoff** [comment] 2018-02-05 21:31
from: @philbooth is keeping an eye on this

**Comment by philbooth** [comment] 2018-02-12 12:17
The numbers seem to be holding up, closing this.

**Closed by philbooth** 2018-02-12 12:17 UTC
Labels: train-107, waffle:next
