### ISSUE TITLE
Malformed event 'fxa_login - blocked'

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-amplitude-send#17] opened 2017-10-02 17:38 UTC
This event is being skipped because it doesn't have any of the `*_id` properties

**Comment by philbooth** [comment] 2017-10-03 13:08
I think these are a consequence of genuine bad requests and can be ignored. But they may indicate something else is wrong with how we're processing the logs, which we should get to the bottom of.

Firstly, I do see good instances of this event showing up in Amplitude:

<img width="201" alt="Screen shot showing a chart of `fxa_login - blocked` events in Amplitude" src="https://user-images.githubusercontent.com/64367/31124581-fdc38c02-a83c-11e7-8b20-6fcf1ef3843b.png" />

So we know it's not an across-the-board problem.

Secondly, regarding the missing ids, it is expected for them not to have a `user_id` because they're emitted before sign-in occurs (obviously). The malformedness is caused by a missing `device_id`, which is optional in the payload schema. And, because this event is necessarily emitted before any authentication occurs, there's nothing to filter out genuinely bad traffic from triggering it.

However, the `log.amplitudeEvent` method does contain [logic that should mean these events never make it into the logs](https://github.com/mozilla/fxa-auth-server/blob/f4c54dae72aa1a89660bf5701c1724256967d0cb/lib/log.js#L162-L165):

```js
Lug.prototype.amplitudeEvent = function (data) {
  if (! data || ! data.event_type || (! data.device_id && ! data.user_id)) {
    this.error({ op: 'log.amplitudeEvent', data })
    return
  }

  this.logger.info('amplitudeEvent', data)
}
```

@jbuck, is it possible that we're also seeing lines from the `log.amplitudeEvent` error here showing up in the filtered batches that get passed to the Lambda function?

**Comment by philbooth** [comment] 2017-10-06 07:09
@jbuck, did you get a chance to look at the logs for this to see if the malformed event objects are coming from those error messages?

**Comment by jbuck** [comment] 2017-10-06 20:41
Looks like it is coming from the error:

`{"Timestamp":1507322154230000000,"Logger":"fxa-auth-server","Type":"log.amplitudeEvent","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"op":"log.amplitudeEvent","data":"{\"time\":1507322154230,\"event_type\":\"fxa_login - blocked\",\"event_properties\":{},\"user_properties\":{},\"app_version\":\"96\",\"language\":\"en\",\"country\":\"United States\",\"region\":\"California\",\"os_name\":\"Android\"}"}}`

**Comment by philbooth** [comment] 2017-10-07 07:43
Thanks @jbuck! Can we tweak the filtering so that it ditches these, or should I tag an auth server 97.3 release that changes `op` to something different/more errory?

**Comment by philbooth** [comment] 2017-10-17 08:36
> Can we tweak the filtering so that it ditches these, or should I tag an auth server 97.3 release that changes `op` to something different/more errory?

In the meeting yesterday, @jbuck suggested fixing the error messages rather than the filtering, so that was done in mozilla/fxa-auth-server#2169. Closing this.

**Closed by philbooth** 2017-10-17 08:36 UTC
Labels: train-98, waffle:active
