### ISSUE TITLE
re-audit about:welcome events in Amplitude

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#74] opened 2018-07-25 17:07 UTC
Summary of Slack conversation with Vlad and Leif:

about:welcome is passing us form views via GET (actually, I have a feeling they're flow_begins)
https://bugzilla.mozilla.org/show_bug.cgi?id=1471514

When we look at Amplitude, we have less form views than reg or login views (which are step 2) and less than successful logins and registrations via `utm_source=activity_stream`

https://analytics.amplitude.com/mozilla-corp/chart/new/3g2lplh

Let's figure out why we are not tracking this properly in Amplitude. Apologies if this is a duplicate bug.

**Comment by davismtl** [comment] 2018-07-25 17:07
CC @irrationalagent @vladikoff

**Comment by vladikoff** [comment] 2018-07-25 17:35
Alex asks: Why are there `email-first` events for activity-stream right now,  even though we just have `begin` and then `signin` or `signup?

**Comment by irrationalagent** [comment] 2018-07-25 17:47
the flow event name view name for email first would be `flow.enter-email`
https://github.com/mozilla/fxa-content-server/blob/0921bc53e92f3b8e4e796f51cc46202d1cfae25e/server/lib/flow-event.js#L109

**Comment by irrationalagent** [comment] 2018-07-30 15:45
probably have to add something here https://github.com/mozilla/fxa-content-server/blob/0921bc53e92f3b8e4e796f51cc46202d1cfae25e/server/lib/flow-event.js

**Comment by vladikoff** [comment] 2018-08-23 23:04
waiting for train-119 to deploy

**Comment by vladikoff** [comment] 2018-09-04 16:01
Not seeing these events in Nightly even though it should be in train-119

**Comment by irrationalagent** [comment] 2018-09-04 16:26
is this `utm_source = activity-stream` and `entrypoint = activity-stream-firstrun` ?

**Comment by philbooth** [comment] 2018-09-04 16:37
This is the equivalent Redash chart for what Alex just showed in the meeting:

https://sql.telemetry.mozilla.org/queries/58750/source#152301

It's per day, so you can see a jump on the far right which is presumably what we were looking for?

**Comment by irrationalagent** [comment] 2018-09-04 16:39
yea, so it seems something is causing them not to get to amplitude.

**Comment by irrationalagent** [comment] 2018-09-04 17:17
hmm.. maybe below should this should be `screen.enter-email.view` ?

https://github.com/mozilla/fxa-content-server/blob/c2d30b9588226dcb9ec60388f59b083bd4d52d03/server/lib/routes/get-metrics-flow.js#L14

because for view events to end up in amplitude apparently it has to pass through this?

https://github.com/mozilla/fxa-content-server/blob/0921bc53e92f3b8e4e796f51cc46202d1cfae25e/server/lib/amplitude.js#L81-L84 

and then usually, for the non-amplitude flow events, `screen` changes to `flow` here:

https://github.com/mozilla/fxa-content-server/blob/0921bc53e92f3b8e4e796f51cc46202d1cfae25e/server/lib/flow-event.js#L155-L159

**Comment by philbooth** [comment] 2018-09-04 17:27
Nah, we don't do fault/blame here! And pretty sure I'd have made the same mistake myself, I completely forgot about the `screen` => `flow` transformation. (and actually I did make the same mistake, because I reviewed Vlad's PR)

**Comment by irrationalagent** [comment] 2018-09-12 18:58
Well, the fix definitely helped things, but according to amplitude we are still seeing substantially more login and registration form views than email-first form views on about:welcome: https://analytics.amplitude.com/mozilla-corp/chart/s3o1wyz

Obviously this shouldn't be happening - email-first form views should always be higher than reg and login form views.

Re:dash seems to disagree, however, with login and reg form views in the hundreds: 
https://sql.telemetry.mozilla.org/queries/58886/source#152577

The email first form views for utm_source = activity-stream seem to be on the same magnitude between re:dash and amplitude. @davismtl do we have any idea the scale of users who would be seeing the about:welcome page? is this page opening for all new installs? or is it landed on infrequently? if the latter, then the redash numbers make more sense. the proportion of login and reg views out of email first views there is similar to what we have in seen on firstrun in the past. either way something is wrong, we are either:

1. overcounting reg/login views for `utm_source` = `firstrun` on amplitude if the email-first form views are in the right ballpark

2. undercounting everything (reg/login form views and email-first form views) on re:dash if the reg/login form views on amplitude are in the right ballpark.

**Comment by davismtl** [comment] 2018-09-12 20:01
Could there be something related to tracking protection that is preventing us from measuring the email_first form views?

**Comment by irrationalagent** [comment] 2018-09-12 21:38
see https://bugzilla.mozilla.org/show_bug.cgi?id=1490826 I'm fairly confident that this is not due to us, but let's keep this open until confirmed

**Comment by vladikoff** [comment] 2018-09-19 15:43
7.6% of users who loaded `about:welcome` reported a `"FXA_METRICS_ERROR"` (from https://github.com/mozilla/activity-stream/blob/847d2292b5aac0a1a35a122c523b2fc46a344dd7/content-src/components/StartupOverlay/StartupOverlay.jsx#L36) in release channel on 13th Sep

**Comment by irrationalagent** [comment] 2018-09-19 15:56
hey @vladikoff how did you get at that data? tried and failed, a-s folks told me it wasn't accessible by re:dash or spark

**Comment by vladikoff** [comment] 2018-09-19 16:01
@irrationalagent via @ncloudioj 🔍

**Comment by irrationalagent** [comment] 2018-09-19 16:03
👍 thanks @ncloudioj

**Comment by ncloudioj** [comment] 2018-09-19 17:37
NP! @irrationalagent 

We've fixed that ping in https://github.com/mozilla/activity-stream/pull/4427, it will be available on redash soon.

**Comment by shane-tomlinson** [comment] 2018-09-20 10:00
@vladikoff and @ncloudioj - thanks for the info, do we have any idea why that many folks are having problems with the request? It looks like the Telemetry ping logs a generic event w/o any details of the error.

**Comment by vladikoff** [comment] 2018-10-01 20:53
waiting for FF63-64 uplift...

**Closed** 2018-10-03 09:17 UTC
Labels: waffle:blocked
